[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g pnpm@latest"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build --filter=@tradescribe/web"]

[start]
cmd = "pnpm --filter @tradescribe/web start"
