ALTER TYPE "TradingPlatform" ADD VALUE IF NOT EXISTS 'CTRADER';
ALTER TYPE "TradingPlatform" ADD VALUE IF NOT EXISTS 'DXTRADE';
ALTER TYPE "TradingPlatform" ADD VALUE IF NOT EXISTS 'MATCHTRADER';
ALTER TYPE "TradingPlatform" ADD VALUE IF NOT EXISTS 'CSV';
